function [A,B,C,D,E,F] = ode45essentials(in1,lambda2,r,h,P,MU,in7,in8)
%ODE45ESSENTIALS
%    [A,B,C,D,E,F] = ODE45ESSENTIALS(IN1,LAMBDA2,R,H,P,MU,IN7,IN8)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    04-Jan-2018 20:18:12

alpha1 = in8(:,1);
alpha2 = in8(:,2);
alpha3 = in8(:,3);
eta = in1(:,3);
mu1 = in7(:,1);
mu2 = in7(:,2);
mu3 = in7(:,3);
u = in1(:,1);
v = in1(:,2);
w = in1(:,4);
t2 = lambda2+v;
t3 = t2.^2;
t4 = w.^2;
t5 = t3+t4;
t6 = 1.0./sqrt(t5);
t7 = alpha1-1.0;
t8 = sqrt(t5);
t9 = 1.0./lambda2.^2;
t10 = 1.0./lambda2;
t11 = t6.*t10;
t12 = alpha2-1.0;
t13 = 1.0./t5.^(3.0./2.0);
t14 = alpha3-1.0;
t15 = alpha1-2.0;
t16 = t8.^t15;
t17 = alpha2-2.0;
t18 = t8.^t17;
t19 = alpha3-2.0;
t20 = t8.^t19;
t21 = t11.^t7;
t22 = t11.^t12;
t23 = t11.^t14;
t24 = t8.^t7;
t25 = t11.^alpha1;
t36 = t6.*t25;
t26 = t24-t36;
t27 = t8.^t12;
t28 = t11.^alpha2;
t38 = t6.*t28;
t29 = t27-t38;
t30 = mu2.*t29;
t31 = t8.^t14;
t32 = t11.^alpha3;
t39 = t6.*t32;
t33 = t31-t39;
t34 = mu3.*t33;
t37 = mu1.*t26;
t35 = t30+t34+t37;
t40 = 1.0./lambda2.^3;
t41 = mu1.*t6.*t7.*t16;
t42 = alpha1.*mu1.*t9.*t13.*t21;
t43 = t41+t42;
t44 = mu2.*t6.*t12.*t18;
t45 = alpha2.*mu2.*t9.*t13.*t22;
t46 = t44+t45;
t47 = mu3.*t6.*t14.*t20;
t48 = alpha3.*mu3.*t9.*t13.*t23;
t49 = t47+t48;
t50 = t8-t3.*t6;
t51 = 1.0./t5;
t52 = eta-h;
t53 = u.^2;
t54 = t52.^2;
t55 = r.*t2.*t43;
t56 = r.*t2.*t46;
t57 = r.*t2.*t49;
t58 = t55+t56+t57;
A = t2.*t6.*t58+r.*t35.*t50.*t51;
if nargout > 1
    t59 = mu1.*r.*t6.*t7.*t16.*w;
    t60 = mu2.*r.*t6.*t12.*t18.*w;
    t61 = mu3.*r.*t6.*t14.*t20.*w;
    t62 = alpha1.*mu1.*r.*t9.*t13.*t21.*w;
    t63 = alpha2.*mu2.*r.*t9.*t13.*t22.*w;
    t64 = alpha3.*mu3.*r.*t9.*t13.*t23.*w;
    t65 = t59+t60+t61+t62+t63+t64;
    B = t2.*t6.*t65-r.*t2.*t13.*t35.*w;
end
if nargout > 2
    t66 = mu1.*t9.*t25;
    t67 = alpha1.*mu1.*t6.*t21.*t40;
    t68 = t66+t67;
    t69 = t68.*v;
    t70 = mu2.*t9.*t28;
    t71 = alpha2.*mu2.*t6.*t22.*t40;
    t72 = t70+t71;
    t73 = t72.*v;
    t74 = mu3.*t9.*t32;
    t75 = alpha3.*mu3.*t6.*t23.*t40;
    t76 = t74+t75;
    t77 = t76.*v;
    t78 = t2.*t43.*v;
    t79 = t2.*t46.*v;
    t80 = t2.*t49.*v;
    t81 = t69+t73+t77+t78+t79+t80;
    t82 = t53+t54;
    t83 = 1.0./t82.^5;
    C = mu1.*(lambda2.^t7-t10.*t25)+mu2.*(lambda2.^t12-t10.*t28)+mu3.*(lambda2.^t14-t10.*t32)+P.*u.*w-t2.*t6.*t35-t2.*t6.*t81-t35.*t50.*t51.*v+MU.*r.*t83.*u.*(t53+t54.*5.0).*3.0;
end
if nargout > 3
    D = t6.*t58.*w-r.*t2.*t13.*t35.*w;
end
if nargout > 4
    E = r.*t6.*t35+t6.*t65.*w-r.*t4.*t13.*t35;
end
if nargout > 5
    F = -P.*t2.*u-t6.*t35.*w-t6.*t81.*w+MU.*r.*t52.*t54.*t83.*1.2e1+t2.*t13.*t35.*v.*w;
end
