function [P1,P2,P3,P4,dP1,dP2,dP3,dP4,Q1,Q2,Q3,Q4] = PdPQ(in1,r,h,P,chixMU,in6,in7)
%PDPQ
%    [P1,P2,P3,P4,DP1,DP2,DP3,DP4,Q1,Q2,Q3,Q4] = PDPQ(IN1,R,H,P,CHIXMU,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    08-Jan-2018 17:30:18

alpha1 = in7(:,1);
alpha2 = in7(:,2);
alpha3 = in7(:,3);
d2eta = in1(:,7);
d3eta = in1(:,8);
d2rho = in1(:,3);
d3rho = in1(:,4);
deta = in1(:,6);
drho = in1(:,2);
eta = in1(:,5);
mu1 = in6(:,1);
mu2 = in6(:,2);
mu3 = in6(:,3);
rho = in1(:,1);
t2 = deta.^2;
t3 = drho.^2;
t4 = t2+t3;
t5 = 1.0./sqrt(t4);
t6 = 1.0./rho;
t7 = r.*t5.*t6;
t8 = sqrt(t4);
t9 = alpha1-1.0;
t10 = 1.0./t4;
t11 = t7.^alpha1;
t12 = alpha2-1.0;
t13 = t7.^alpha2;
t14 = alpha3-1.0;
t15 = t7.^alpha3;
t16 = t5.*t11;
t17 = t8.^t9;
t18 = t16-t17;
t19 = mu1.*t18;
t20 = t5.*t13;
t21 = t8.^t12;
t22 = t20-t21;
t23 = mu2.*t22;
t24 = t5.*t15;
t25 = t8.^t14;
t26 = t24-t25;
t27 = mu3.*t26;
t28 = t19+t23+t27;
t29 = 1.0./d2rho;
t30 = 1.0./t4.^(3.0./2.0);
t31 = alpha1-2.0;
t32 = t8.^t31;
t33 = t9.*t32;
t34 = alpha1+1.0;
t35 = t10.*t11.*t34;
t36 = t33+t35;
t37 = mu1.*t36;
t38 = alpha2-2.0;
t39 = t8.^t38;
t40 = t12.*t39;
t41 = alpha2+1.0;
t42 = t10.*t13.*t41;
t43 = t40+t42;
t44 = mu2.*t43;
t45 = alpha3-2.0;
t46 = t8.^t45;
t47 = t14.*t46;
t48 = alpha3+1.0;
t49 = t10.*t15.*t48;
t50 = t47+t49;
t51 = mu3.*t50;
t52 = t37+t44+t51;
t53 = deta.*t5.*t29;
t54 = 1.0./d2eta;
t55 = drho.*t5.*t54;
t85 = deta.*drho.*r.*t30;
t56 = t53+t55-t85;
t57 = deta.*drho.*r.*t10.*t52;
t58 = t57-t28.*t56;
t59 = r.*t5;
t60 = d2eta.*deta;
t61 = d2rho.*drho;
t62 = t60+t61;
t63 = drho.*t5.*t29.*2.0;
t64 = t59+t63-r.*t3.*t30;
P1 = -t28.*t64+r.*t3.*t10.*t52;
if nargout > 1
    P2 = t58;
end
if nargout > 2
    P3 = t58;
end
if nargout > 3
    t65 = 1.0./r;
    t66 = rho.*t65;
    t67 = 1.0./r.^2;
    t79 = drho.*r;
    t68 = rho-t79;
    t69 = t7.^t34;
    t70 = t7.^t41;
    t71 = t7.^t48;
    t72 = t4.^(3.0./2.0);
    t73 = 1.0./t4.^3;
    t74 = 1.0./d2rho.^2;
    t75 = d3rho.*t8;
    t76 = d2rho.*t5.*t62;
    t77 = t75+t76;
    t78 = 1.0./t4.^2;
    t80 = alpha1.*mu1.*t69;
    t81 = alpha2.*mu2.*t70;
    t82 = alpha3.*mu3.*t71;
    t83 = t80+t81+t82;
    t144 = t5.*t52.*t62;
    t145 = t67.*t68.*t83;
    t84 = t144-t145;
    t86 = alpha1-3.0;
    t87 = t8.^t86;
    t88 = t9.*t31.*t87;
    t89 = -alpha1-3.0;
    t90 = t8.^t89;
    t91 = t66.^(-alpha1);
    t92 = alpha1+2.0;
    t147 = t34.*t90.*t91.*t92;
    t93 = t88-t147;
    t94 = mu1.*t93;
    t95 = alpha2-3.0;
    t96 = t8.^t95;
    t97 = t12.*t38.*t96;
    t98 = -alpha2-3.0;
    t99 = t8.^t98;
    t100 = t66.^(-alpha2);
    t101 = alpha2+2.0;
    t148 = t41.*t99.*t100.*t101;
    t102 = t97-t148;
    t103 = mu2.*t102;
    t104 = alpha3-3.0;
    t105 = t8.^t104;
    t106 = t14.*t45.*t105;
    t107 = -alpha3-3.0;
    t108 = t8.^t107;
    t109 = t66.^(-alpha3);
    t110 = alpha3+2.0;
    t149 = t48.*t108.*t109.*t110;
    t111 = t106-t149;
    t112 = mu3.*t111;
    t113 = t94+t103+t112;
    t114 = t5.*t62.*t113;
    t115 = alpha1.*mu1.*t5.*t34.*t69;
    t116 = alpha2.*mu2.*t5.*t41.*t70;
    t117 = alpha3.*mu3.*t5.*t48.*t71;
    t118 = t115+t116+t117;
    t119 = t67.*t68.*t118;
    t120 = t114+t119;
    t121 = deta.*drho;
    t122 = d2rho.*deta.*r;
    t123 = d2eta.*drho.*r;
    t124 = t121+t122+t123;
    t125 = t72.*t124;
    t126 = t125-deta.*drho.*r.*t8.*t62.*3.0;
    t127 = t73.*t126;
    t128 = deta.*t77;
    t136 = d2eta.*d2rho.*t8;
    t129 = t128-t136;
    t130 = t10.*t74.*t129;
    t131 = 1.0./d2eta.^2;
    t132 = d3eta.*t8;
    t133 = d2eta.*t5.*t62;
    t134 = t132+t133;
    t135 = drho.*t134;
    t137 = deta.*drho.*t10;
    t138 = d2rho.*deta;
    t139 = d2eta.*drho;
    t140 = t138+t139;
    t141 = r.*t10.*t140;
    t142 = t137+t141-deta.*drho.*r.*t62.*t78.*2.0;
    t143 = t52.*t142;
    t146 = t56.*t84;
    t150 = deta.*drho.*r.*t10.*t120;
    t151 = r.*t30.*t62;
    t152 = deta.*t5.*t54.*2.0;
    t153 = t59+t152-r.*t2.*t30;
    P4 = -t28.*t153+r.*t2.*t10.*t52;
end
if nargout > 4
    dP1 = t64.*t84+t28.*(-t5+t151+t73.*(t72.*(t3+d2rho.*drho.*r.*2.0)-r.*t3.*t8.*t62.*3.0)+t10.*t74.*(drho.*t77-d2rho.^2.*t8).*2.0)+t52.*(t3.*t10+d2rho.*drho.*r.*t10.*2.0-r.*t3.*t62.*t78.*2.0)+r.*t3.*t10.*t120;
end
if nargout > 5
    dP2 = t143+t146+t150+t28.*(t127+t130+t10.*t131.*(t135-d2eta.*d2rho.*t8));
end
if nargout > 6
    dP3 = t143+t146+t150+t28.*(t127+t130+t10.*t131.*(t135-t136));
end
if nargout > 7
    dP4 = t84.*t153+t28.*(-t5+t151+t73.*(t72.*(t2+d2eta.*deta.*r.*2.0)-r.*t2.*t8.*t62.*3.0)+t10.*t131.*(deta.*t134-d2eta.^2.*t8).*2.0)+t52.*(t2.*t10+d2eta.*deta.*r.*t10.*2.0-r.*t2.*t62.*t78.*2.0)+r.*t2.*t10.*t120;
end
if nargout > 8
    t154 = r.^2;
    t155 = 1.0./rho.^2;
    t156 = t66.^t9;
    t157 = t156-r.*t6.*t11;
    t158 = mu1.*t157;
    t159 = t66.^t12;
    t160 = t159-r.*t6.*t13;
    t161 = mu2.*t160;
    t162 = t66.^t14;
    t163 = t162-r.*t6.*t15;
    t164 = mu3.*t163;
    t165 = t158+t161+t164;
    t166 = 1.0./drho.^2;
    t167 = eta-h;
    t168 = rho.^2;
    t169 = t167.^2;
    t170 = t168+t169;
    t171 = 1.0./t170.^4;
    t172 = 1.0./t170.^5;
    t173 = t169.*4.0;
    t174 = t168+t173;
    t175 = eta.*2.0;
    t176 = h.*2.0;
    t177 = t175-t176;
    t178 = eta.*8.0;
    t179 = h.*8.0;
    t180 = t178-t179;
    t181 = 1.0./t170.^6;
    t182 = t171.*2.0;
    t183 = t168.*t174.*t181.*8.0e1;
    t195 = t172.*t174.*8.0;
    t196 = t168.*t172.*3.2e1;
    t184 = t182+t183-t195-t196;
    t185 = 1.0./drho;
    t186 = rho.*t171.*2.0;
    t188 = rho.*t172.*t174.*8.0;
    t187 = t186-t188;
    t189 = 1.0./drho.^3;
    t190 = alpha1.*mu1.*r.*t6.*t34.*t69;
    t191 = alpha2.*mu2.*r.*t6.*t41.*t70;
    t192 = alpha3.*mu3.*r.*t6.*t48.*t71;
    t193 = t190+t191+t192;
    t194 = t5.*t62.*t118;
    t197 = drho.*t184;
    t198 = rho.*t172.*t177.*8.0;
    t199 = rho.*t172.*t180.*8.0;
    t201 = rho.*t174.*t177.*t181.*4.0e1;
    t200 = t198+t199-t201;
    t202 = t171.*t180;
    t205 = t172.*t174.*t177.*4.0;
    t203 = t202-t205;
    t204 = chixMU.*r.*t200.*(1.0./2.0);
    t206 = 1.0./deta;
    t207 = t171.*8.0;
    t208 = t177.^2;
    t209 = t172.*t177.*t180.*8.0;
    t215 = t174.*t181.*t208.*2.0e1;
    t210 = t195-t207+t209-t215;
    t211 = deta.*t203;
    t212 = drho.*t187;
    t213 = t211+t212;
    Q1 = P.*deta-t83.*(d2rho.*t5-drho.*t30.*t62)-t5.*t84+t65.*(mu1.*(t9.*t66.^t31+t11.*t34.*t154.*t155)+mu2.*(t12.*t66.^t38+t13.*t41.*t154.*t155)+mu3.*(t14.*t66.^t45+t15.*t48.*t154.*t155))-t166.*(t5.*t28.*t62+t67.*t68.*t165)+chixMU.*t29.*(t197-deta.*t200).*(1.0./2.0)-chixMU.*r.*t184.*(1.0./2.0)-chixMU.*t185.*t187-chixMU.*t166.*t213.*(1.0./2.0)-t28.*t30.*t62+t65.*t165.*t185+drho.*t5.*(t194-t67.*t68.*t193)-d2rho.*t189.*((mu1.*(t11+t8.^alpha1+t66.^alpha1-3.0).*2.0)./alpha1+(mu2.*(t13+t8.^alpha2+t66.^alpha2-3.0).*2.0)./alpha2+(mu3.*(t15+t8.^alpha3+t66.^alpha3-3.0).*2.0)./alpha3)-chixMU.*d3rho.*t74.*t187.*(1.0./2.0)+chixMU.*d2rho.*t171.*t174.*t189;
end
if nargout > 9
    Q2 = t204-P.*drho-t83.*(d2eta.*t5-deta.*t30.*t62)-t28.*(d2rho.*deta.*t5.*t166+deta.*t30.*t62.*t185-(d2eta.*t8.*t185)./t62)+chixMU.*t54.*(t197-deta.*t200).*(1.0./2.0)-chixMU.*t185.*t203.*(1.0./2.0)-chixMU.*t187.*t206.*(1.0./2.0)+deta.*t5.*(t194-t67.*t68.*t193)-chixMU.*d3eta.*t131.*t187.*(1.0./2.0)-deta.*t5.*t84.*t185;
end
if nargout > 10
    t214 = drho.*t200;
    t216 = deta.*t210;
    t217 = t214+t216;
    Q3 = t204-chixMU.*t29.*t217.*(1.0./2.0)-chixMU.*t185.*t203.*(1.0./2.0)-chixMU.*t187.*t206.*(1.0./2.0)-chixMU.*d3rho.*t74.*t203.*(1.0./2.0);
end
if nargout > 11
    Q4 = chixMU.*r.*t210.*(1.0./2.0)-chixMU.*t54.*t217.*(1.0./2.0)-chixMU.*t203.*t206-chixMU.*1.0./deta.^2.*t213.*(1.0./2.0)-chixMU.*d3eta.*t131.*t203.*(1.0./2.0)+chixMU.*d2eta.*1.0./deta.^3.*t171.*t174;
end
